### ISSUE TITLE
"Stage 1 BART VAE Finetuning" doesn't work.

### ISSUE THREAD

**Issue by hibikaze-git** [ImKeTT/pcae#2]
Thank you for a great job.
"Stage 1 BART VAE Finetuning" doesn't work on latest commit.
`RuntimeError: mat1 and mat2 shapes cannot be multiplied (16x16 and 768x768)`

Undoing the commit below seems to work.
https://github.com/ImKeTT/pcae/commit/c05f708cb17a1e51f852638ed25d0b4641576427

How can I fix it?

**Comment by ImKeTT** [comment]
Thanks for your interests. Apologize for the inconvenience caused by this glitch. We have fixed it and uploaded the latest version. 

We added two options for the bart pooler: 1) the first token pooling as in the Optimus (also the one used in our paper); 2) the mean pooling method across the input tokens, which we later found more stable during model training. You can easily switch  between these two modes by twitching the argument '--first_token_pooling' in command line (which works [here](https://github.com/ImKeTT/pcae/blob/72c553acb51acfa22f5e6db38ea4324a5fef0e7f/vae.py#L24)). Plz let me know if there's further questions.

[In addition, both 'first token pooling' and 'mean pooling' are simple and intuitive methods for connecting token and the latent space, you can also check our new _Latent Attention_ in [AdaVAE](https://github.com/ImKeTT/adavae) for building a more meaningful latent representation in VAE if ur interested!]

**Comment by hibikaze-git** [comment]
Thanks for the quick response and additional interesting information!
